/**
 * Markdown Reporter - Generates PR-friendly markdown reports
 */

import {
  AnalysisResult,
  PackageAnalysis,
  ApiChange,
  ChangeSeverity,
  ChangeType,
} from "../types.js";
import { VersionAnalyzer } from "../analyzers/version.js";

/**
 * Options for the markdown reporter
 */
export interface MarkdownReporterOptions {
  /** Maximum changes to show before collapsing */
  collapseThreshold?: number;
  /** Whether to include the footer */
  includeFooter?: boolean;
  /**
   * Maximum number of lines kept verbatim in a single before/after snippet.
   * Longer snippets are shown head + tail with the middle elided, wrapped in
   * a collapsible <details> block. Keeps the report under GitHub's 65 KB
   * comment limit on packages with huge object-literal types.
   */
  snippetMaxLines?: number;
}

/**
 * Reporter that generates GitHub-flavored markdown from analysis results
 */
export class MarkdownReporter {
  private collapseThreshold: number;
  private includeFooter: boolean;
  private snippetMaxLines: number;
  private versionAnalyzer = new VersionAnalyzer();

  constructor(options: MarkdownReporterOptions = {}) {
    this.collapseThreshold = options.collapseThreshold ?? 10;
    this.includeFooter = options.includeFooter ?? true;
    this.snippetMaxLines = options.snippetMaxLines ?? 60;
  }

  /**
   * Generate full markdown report from analysis result
   */
  generate(result: AnalysisResult): string {
    const sections: string[] = [];

    // Header
    sections.push("# API Changes Report\n");
    sections.push(`> Generated by snapi on ${result.timestamp}\n`);

    // Summary
    sections.push(this.generateSummary(result));

    const aiModel = this.firstAiModel(result);
    if (aiModel) {
      sections.push(`> 🤖 This report was reviewed by \`${aiModel}\`.\n`);
    }

    // Package sections
    const packagesWithChanges = result.packages.filter(
      (p) => p.changes.length > 0,
    );

    if (packagesWithChanges.length === 0) {
      sections.push("## No API Changes Detected\n");
      sections.push(
        "All packages have stable APIs with no detected changes.\n",
      );
    } else {
      for (const pkg of packagesWithChanges) {
        sections.push("---\n");
        sections.push(this.generatePackageSection(pkg));
      }
    }

    // Footer
    if (this.includeFooter) {
      sections.push("---\n");
      sections.push(
        "*Report generated by [snapi](https://github.com/clerk/snapi)*\n",
      );
    }

    return sections.join("\n");
  }

  /**
   * Generate JSON output (alternative format)
   */
  generateJson(result: AnalysisResult): string {
    return JSON.stringify(result, null, 2);
  }

  /**
   * Generate the summary section
   */
  private generateSummary(result: AnalysisResult): string {
    const lines: string[] = [];

    lines.push("## Summary\n");
    lines.push("| Metric | Count |");
    lines.push("|--------|-------|");
    lines.push(`| Packages analyzed | ${result.summary.totalPackages} |`);
    lines.push(
      `| Packages with changes | ${result.summary.packagesWithChanges} |`,
    );
    lines.push(
      `| ${this.getTypeBadge(ChangeType.BREAKING)} Breaking changes | ${result.summary.breakingChanges} |`,
    );
    lines.push(
      `| ${this.getTypeBadge(ChangeType.NON_BREAKING)} Non-breaking changes | ${result.summary.nonBreakingChanges} |`,
    );
    lines.push(
      `| ${this.getTypeBadge(ChangeType.ADDITION)} Additions | ${result.summary.additions} |`,
    );
    lines.push("");

    // Warning message if breaking changes
    if (result.hasBreakingChanges) {
      lines.push(
        `> **Warning**\n> ${result.summary.breakingChanges} breaking change(s) detected - Major version bump required\n`,
      );
    }

    return lines.join("\n");
  }

  /**
   * Generate section for a single package
   */
  private generatePackageSection(pkg: PackageAnalysis): string {
    const lines: string[] = [];

    // Package header
    lines.push(`## ${pkg.packageName}\n`);

    // Version info. When previous === current the PR hasn't bumped yet, so an
    // arrow would be misleading; show the current version and project the
    // target version implied by the recommended bump instead.
    const versionUnchanged = pkg.version.previous === pkg.version.current;
    if (versionUnchanged) {
      lines.push(`**Current version:** ${pkg.version.current}`);
    } else {
      lines.push(
        `**Version:** ${pkg.version.previous} → ${pkg.version.current}`,
      );
    }

    const bumpLabel = pkg.recommendedVersionBump.toUpperCase();
    const targetVersion = versionUnchanged
      ? this.versionAnalyzer.applyBump(
          pkg.version.current,
          pkg.recommendedVersionBump,
        )
      : null;
    lines.push(
      targetVersion
        ? `**Recommended bump:** ${bumpLabel} → ${targetVersion}`
        : `**Recommended bump:** ${bumpLabel}`,
    );

    if (pkg.actualVersionBump) {
      const bumpIndicator = pkg.isValidBump ? "✅" : "❌";
      const suffix = pkg.isValidBump ? "" : " (insufficient)";
      lines.push(
        `**Actual bump:** ${pkg.actualVersionBump.toUpperCase()} ${bumpIndicator}${suffix}`,
      );
    }
    lines.push("");

    // Group changes by subpath. A package using only the root export emits
    // no subpath subheader to preserve the original report shape.
    const subpathGroups = new Map<string, ApiChange[]>();
    for (const change of pkg.changes) {
      const key = change.subpath ?? ".";
      const bucket = subpathGroups.get(key);
      if (bucket) bucket.push(change);
      else subpathGroups.set(key, [change]);
    }

    const orderedSubpaths = Array.from(subpathGroups.keys()).sort((a, b) => {
      if (a === b) return 0;
      if (a === ".") return -1;
      if (b === ".") return 1;
      return a.localeCompare(b);
    });

    const onlyRoot = orderedSubpaths.length === 1 && orderedSubpaths[0] === ".";

    for (const subpath of orderedSubpaths) {
      const changes = subpathGroups.get(subpath) ?? [];
      if (changes.length === 0) continue;

      if (!onlyRoot) {
        lines.push(`### Subpath \`${subpath}\`\n`);
      }

      lines.push(this.generateGroupedSections(changes, onlyRoot ? 3 : 4));
    }

    return lines.join("\n");
  }

  /**
   * Render breaking / non-breaking / additions sections for a single bucket
   * of changes (used per subpath group).
   */
  private generateGroupedSections(
    changes: ApiChange[],
    headingLevel: number,
  ): string {
    const lines: string[] = [];

    const breaking = changes.filter((c) => c.type === ChangeType.BREAKING);
    const nonBreaking = changes.filter(
      (c) => c.type === ChangeType.NON_BREAKING,
    );
    const additions = changes.filter((c) => c.type === ChangeType.ADDITION);

    if (breaking.length > 0) {
      lines.push(
        this.generateChangeSection(
          `${this.getTypeBadge(ChangeType.BREAKING)} Breaking Changes`,
          breaking,
          headingLevel,
        ),
      );
    }
    if (nonBreaking.length > 0) {
      lines.push(
        this.generateChangeSection(
          `${this.getTypeBadge(ChangeType.NON_BREAKING)} Non-breaking Changes`,
          nonBreaking,
          headingLevel,
        ),
      );
    }
    if (additions.length > 0) {
      lines.push(
        this.generateChangeSection(
          `${this.getTypeBadge(ChangeType.ADDITION)} Additions`,
          additions,
          headingLevel,
        ),
      );
    }

    return lines.join("\n");
  }

  /**
   * Generate a section for a group of changes
   */
  private generateChangeSection(
    title: string,
    changes: ApiChange[],
    headingLevel: number = 3,
  ): string {
    const lines: string[] = [];

    const hashes = "#".repeat(headingLevel);
    lines.push(`${hashes} ${title} (${changes.length})\n`);

    // Use collapsible section if too many changes
    const shouldCollapse = changes.length > this.collapseThreshold;

    if (shouldCollapse) {
      lines.push("<details>");
      lines.push(
        `<summary>Click to expand ${changes.length} changes</summary>\n`,
      );
    }

    for (const change of changes) {
      lines.push(this.formatChange(change, headingLevel + 1));
    }

    if (shouldCollapse) {
      lines.push("</details>\n");
    }

    return lines.join("\n");
  }

  /**
   * Format a single change with before/after diff
   */
  private formatChange(change: ApiChange, headingLevel: number = 4): string {
    const lines: string[] = [];

    // Change title
    const action = this.getChangeAction(change.type);
    const tag = this.aiHeadingTag(change);
    const hashes = "#".repeat(headingLevel);
    lines.push(`${hashes} ${action}: \`${change.name}\`${tag}\n`);

    // Code diff
    if (change.beforeSnippet || change.afterSnippet) {
      const beforeLines = change.beforeSnippet
        ? change.beforeSnippet.trim().split("\n")
        : [];
      const afterLines = change.afterSnippet
        ? change.afterSnippet.trim().split("\n")
        : [];
      const oversize =
        beforeLines.length > this.snippetMaxLines ||
        afterLines.length > this.snippetMaxLines;

      if (oversize) {
        lines.push("<details>");
        lines.push(
          `<summary>Diff truncated (before: ${beforeLines.length} lines, after: ${afterLines.length} lines) — click to expand</summary>\n`,
        );
      }

      lines.push("```diff");
      for (const line of this.truncateForDiff(beforeLines)) {
        lines.push(`- ${line}`);
      }
      for (const line of this.truncateForDiff(afterLines)) {
        lines.push(`+ ${line}`);
      }
      lines.push("```");

      if (oversize) {
        lines.push("</details>\n");
      } else {
        lines.push("");
      }
    }

    // Description. When the AI also reviewed this same change, label the
    // rule-based description as the static analyzer's voice so the AI block
    // below reads as a distinct opinion rather than a contradiction.
    const ai = change.aiAnalysis;
    const labelStatic = ai && ai.source !== "ai-discovered";
    const prefix = labelStatic ? "**Static analyzer:** " : "";
    lines.push(`> ${prefix}${change.description}\n`);

    if (ai) {
      const confidence = Math.round(ai.confidence * 100);
      const label = this.aiReviewLabel(change);
      lines.push(`> 🤖 **${label}** (${confidence}%): ${ai.rationale}\n`);
      if (ai.migration) {
        lines.push(`> **Migration:** ${ai.migration}\n`);
      }
    }

    return lines.join("\n");
  }

  /**
   * Trim a snippet to head + tail with an elision marker when it exceeds
   * snippetMaxLines. Returns the original lines untouched when within budget.
   */
  private truncateForDiff(lines: string[]): string[] {
    if (lines.length <= this.snippetMaxLines) return lines;
    const half = Math.max(1, Math.floor(this.snippetMaxLines / 2));
    const head = lines.slice(0, half);
    const tail = lines.slice(lines.length - half);
    const elided = lines.length - head.length - tail.length;
    return [
      ...head,
      `// ... ${elided} more line${elided === 1 ? "" : "s"} elided ...`,
      ...tail,
    ];
  }

  private aiHeadingTag(change: ApiChange): string {
    const ai = change.aiAnalysis;
    if (!ai) return "";
    if (ai.source === "ai-discovered") {
      return ` _(detected by AI)_`;
    }
    return "";
  }

  private aiReviewLabel(change: ApiChange): string {
    const ai = change.aiAnalysis;
    if (!ai) return "AI review";
    switch (ai.source) {
      case "rule-overridden":
        return `AI review (reclassified as ${change.type})`;
      case "rule-confirmed":
        return "AI review (confirmed)";
      case "ai-discovered":
        return "AI review (additional finding)";
    }
  }

  private firstAiModel(result: AnalysisResult): string | null {
    for (const pkg of result.packages) {
      if (pkg.aiReviewedBy) return pkg.aiReviewedBy;
      for (const change of pkg.changes) {
        if (change.aiAnalysis) return change.aiAnalysis.model;
      }
    }
    return null;
  }

  /**
   * Get action word for change type
   */
  private getChangeAction(type: ChangeType): string {
    switch (type) {
      case ChangeType.BREAKING:
        return "Changed";
      case ChangeType.NON_BREAKING:
        return "Modified";
      case ChangeType.ADDITION:
        return "Added";
      default:
        return "Changed";
    }
  }

  /**
   * Get emoji badge for change type
   */
  private getTypeBadge(type: ChangeType): string {
    switch (type) {
      case ChangeType.BREAKING:
        return "🔴";
      case ChangeType.NON_BREAKING:
        return "🟡";
      case ChangeType.ADDITION:
        return "🟢";
      default:
        return "⚪";
    }
  }

  /**
   * Get emoji badge for severity
   */
  getSeverityBadge(severity: ChangeSeverity): string {
    switch (severity) {
      case ChangeSeverity.MAJOR:
        return "🔴";
      case ChangeSeverity.MINOR:
        return "🟡";
      case ChangeSeverity.PATCH:
        return "🟢";
      default:
        return "⚪";
    }
  }
}
