/**
 * Markdown Reporter - Generates PR-friendly markdown reports
 */

import {
  AnalysisResult,
  PackageAnalysis,
  ApiChange,
  ChangeSeverity,
  ChangeType,
} from "../types.js";

/**
 * Options for the markdown reporter
 */
export interface MarkdownReporterOptions {
  /** Maximum changes to show before collapsing */
  collapseThreshold?: number;
  /** Whether to include the footer */
  includeFooter?: boolean;
}

/**
 * Reporter that generates GitHub-flavored markdown from analysis results
 */
export class MarkdownReporter {
  private collapseThreshold: number;
  private includeFooter: boolean;

  constructor(options: MarkdownReporterOptions = {}) {
    this.collapseThreshold = options.collapseThreshold ?? 10;
    this.includeFooter = options.includeFooter ?? true;
  }

  /**
   * Generate full markdown report from analysis result
   */
  generate(result: AnalysisResult): string {
    const sections: string[] = [];

    // Header
    sections.push("# API Changes Report\n");
    sections.push(`> Generated by snapi on ${result.timestamp}\n`);

    // Summary
    sections.push(this.generateSummary(result));

    // Package sections
    const packagesWithChanges = result.packages.filter(
      (p) => p.changes.length > 0,
    );

    if (packagesWithChanges.length === 0) {
      sections.push("## No API Changes Detected\n");
      sections.push(
        "All packages have stable APIs with no detected changes.\n",
      );
    } else {
      for (const pkg of packagesWithChanges) {
        sections.push("---\n");
        sections.push(this.generatePackageSection(pkg));
      }
    }

    // Footer
    if (this.includeFooter) {
      sections.push("---\n");
      sections.push(
        "*Report generated by [snapi](https://github.com/clerk/snapi)*\n",
      );
    }

    return sections.join("\n");
  }

  /**
   * Generate JSON output (alternative format)
   */
  generateJson(result: AnalysisResult): string {
    return JSON.stringify(result, null, 2);
  }

  /**
   * Generate the summary section
   */
  private generateSummary(result: AnalysisResult): string {
    const lines: string[] = [];

    lines.push("## Summary\n");
    lines.push("| Metric | Count |");
    lines.push("|--------|-------|");
    lines.push(`| Packages analyzed | ${result.summary.totalPackages} |`);
    lines.push(
      `| Packages with changes | ${result.summary.packagesWithChanges} |`,
    );
    lines.push(
      `| ${this.getTypeBadge(ChangeType.BREAKING)} Breaking changes | ${result.summary.breakingChanges} |`,
    );
    lines.push(
      `| ${this.getTypeBadge(ChangeType.NON_BREAKING)} Non-breaking changes | ${result.summary.nonBreakingChanges} |`,
    );
    lines.push(
      `| ${this.getTypeBadge(ChangeType.ADDITION)} Additions | ${result.summary.additions} |`,
    );
    lines.push("");

    // Warning message if breaking changes
    if (result.hasBreakingChanges) {
      lines.push(
        `> **Warning**\n> ${result.summary.breakingChanges} breaking change(s) detected - Major version bump required\n`,
      );
    }

    return lines.join("\n");
  }

  /**
   * Generate section for a single package
   */
  private generatePackageSection(pkg: PackageAnalysis): string {
    const lines: string[] = [];

    // Package header
    lines.push(`## ${pkg.packageName}\n`);

    // Version info
    lines.push(`**Version:** ${pkg.version.previous} → ${pkg.version.current}`);
    lines.push(
      `**Recommended bump:** ${pkg.recommendedVersionBump.toUpperCase()}`,
    );

    if (pkg.actualVersionBump) {
      const bumpIndicator = pkg.isValidBump ? "✅" : "❌";
      const suffix = pkg.isValidBump ? "" : " (insufficient)";
      lines.push(
        `**Actual bump:** ${pkg.actualVersionBump.toUpperCase()} ${bumpIndicator}${suffix}`,
      );
    }
    lines.push("");

    // Group changes by type
    const breakingChanges = pkg.changes.filter(
      (c) => c.type === ChangeType.BREAKING,
    );
    const nonBreakingChanges = pkg.changes.filter(
      (c) => c.type === ChangeType.NON_BREAKING,
    );
    const additions = pkg.changes.filter((c) => c.type === ChangeType.ADDITION);

    // Breaking changes
    if (breakingChanges.length > 0) {
      lines.push(
        this.generateChangeSection(
          `${this.getTypeBadge(ChangeType.BREAKING)} Breaking Changes`,
          breakingChanges,
        ),
      );
    }

    // Non-breaking changes
    if (nonBreakingChanges.length > 0) {
      lines.push(
        this.generateChangeSection(
          `${this.getTypeBadge(ChangeType.NON_BREAKING)} Non-breaking Changes`,
          nonBreakingChanges,
        ),
      );
    }

    // Additions
    if (additions.length > 0) {
      lines.push(
        this.generateChangeSection(
          `${this.getTypeBadge(ChangeType.ADDITION)} Additions`,
          additions,
        ),
      );
    }

    return lines.join("\n");
  }

  /**
   * Generate a section for a group of changes
   */
  private generateChangeSection(title: string, changes: ApiChange[]): string {
    const lines: string[] = [];

    lines.push(`### ${title} (${changes.length})\n`);

    // Use collapsible section if too many changes
    const shouldCollapse = changes.length > this.collapseThreshold;

    if (shouldCollapse) {
      lines.push("<details>");
      lines.push(
        `<summary>Click to expand ${changes.length} changes</summary>\n`,
      );
    }

    for (const change of changes) {
      lines.push(this.formatChange(change));
    }

    if (shouldCollapse) {
      lines.push("</details>\n");
    }

    return lines.join("\n");
  }

  /**
   * Format a single change with before/after diff
   */
  private formatChange(change: ApiChange): string {
    const lines: string[] = [];

    // Change title
    const action = this.getChangeAction(change.type);
    lines.push(`#### ${action}: \`${change.name}\`\n`);

    // Code diff
    if (change.beforeSnippet || change.afterSnippet) {
      lines.push("```diff");

      if (change.beforeSnippet) {
        // Add - prefix to each line
        const beforeLines = change.beforeSnippet.trim().split("\n");
        for (const line of beforeLines) {
          lines.push(`- ${line}`);
        }
      }

      if (change.afterSnippet) {
        // Add + prefix to each line
        const afterLines = change.afterSnippet.trim().split("\n");
        for (const line of afterLines) {
          lines.push(`+ ${line}`);
        }
      }

      lines.push("```\n");
    }

    // Description
    lines.push(`> ${change.description}\n`);

    return lines.join("\n");
  }

  /**
   * Get action word for change type
   */
  private getChangeAction(type: ChangeType): string {
    switch (type) {
      case ChangeType.BREAKING:
        return "Changed";
      case ChangeType.NON_BREAKING:
        return "Modified";
      case ChangeType.ADDITION:
        return "Added";
      default:
        return "Changed";
    }
  }

  /**
   * Get emoji badge for change type
   */
  private getTypeBadge(type: ChangeType): string {
    switch (type) {
      case ChangeType.BREAKING:
        return "🔴";
      case ChangeType.NON_BREAKING:
        return "🟡";
      case ChangeType.ADDITION:
        return "🟢";
      default:
        return "⚪";
    }
  }

  /**
   * Get emoji badge for severity
   */
  getSeverityBadge(severity: ChangeSeverity): string {
    switch (severity) {
      case ChangeSeverity.MAJOR:
        return "🔴";
      case ChangeSeverity.MINOR:
        return "🟡";
      case ChangeSeverity.PATCH:
        return "🟢";
      default:
        return "⚪";
    }
  }
}
