/**
 * Markdown Reporter - Generates PR-friendly markdown reports
 */

import {
  AnalysisResult,
  PackageAnalysis,
  ApiChange,
  ChangeSeverity,
  ChangeType,
} from "../types.js";
import { VersionAnalyzer } from "../analyzers/version.js";

/**
 * Options for the markdown reporter
 */
export interface MarkdownReporterOptions {
  /** Maximum changes to show before collapsing */
  collapseThreshold?: number;
  /** Whether to include the footer */
  includeFooter?: boolean;
  /**
   * Visible-line budget for a single before/after diff. When the rendered
   * diff exceeds this, the block is wrapped in a collapsible <details>
   * element. The middle hunk is also bulk-truncated head+tail per side past
   * this budget when no common prefix/suffix exists. Keeps the report under
   * GitHub's 65 KB comment limit on packages with huge object-literal types.
   */
  snippetMaxLines?: number;
}

/**
 * Reporter that generates GitHub-flavored markdown from analysis results
 */
export class MarkdownReporter {
  private collapseThreshold: number;
  private includeFooter: boolean;
  private snippetMaxLines: number;
  private versionAnalyzer = new VersionAnalyzer();

  constructor(options: MarkdownReporterOptions = {}) {
    this.collapseThreshold = options.collapseThreshold ?? 10;
    this.includeFooter = options.includeFooter ?? true;
    this.snippetMaxLines = options.snippetMaxLines ?? 60;
  }

  /**
   * Generate full markdown report from analysis result
   */
  generate(result: AnalysisResult): string {
    const sections: string[] = [];

    // Header
    sections.push("# API Changes Report\n");
    sections.push(`> Generated by snapi on ${result.timestamp}\n`);

    // Summary
    sections.push(this.generateSummary(result));

    const aiModel = this.firstAiModel(result);
    if (aiModel) {
      sections.push(`> 🤖 This report was reviewed by \`${aiModel}\`.\n`);
    }

    // Package sections
    const packagesWithChanges = result.packages.filter(
      (p) => p.changes.length > 0,
    );

    if (packagesWithChanges.length === 0) {
      sections.push("## No API Changes Detected\n");
      sections.push(
        "All packages have stable APIs with no detected changes.\n",
      );
    } else {
      for (const pkg of packagesWithChanges) {
        sections.push("---\n");
        sections.push(this.generatePackageSection(pkg));
      }
    }

    // Footer
    if (this.includeFooter) {
      sections.push("---\n");
      sections.push(
        "*Report generated by [snapi](https://github.com/clerk/snapi)*\n",
      );
    }

    return sections.join("\n");
  }

  /**
   * Generate JSON output (alternative format)
   */
  generateJson(result: AnalysisResult): string {
    return JSON.stringify(result, null, 2);
  }

  /**
   * Generate the summary section
   */
  private generateSummary(result: AnalysisResult): string {
    const lines: string[] = [];

    lines.push("## Summary\n");
    lines.push("| Metric | Count |");
    lines.push("|--------|-------|");
    lines.push(`| Packages analyzed | ${result.summary.totalPackages} |`);
    lines.push(
      `| Packages with changes | ${result.summary.packagesWithChanges} |`,
    );
    lines.push(
      `| ${this.getTypeBadge(ChangeType.BREAKING)} Breaking changes | ${result.summary.breakingChanges} |`,
    );
    lines.push(
      `| ${this.getTypeBadge(ChangeType.NON_BREAKING)} Non-breaking changes | ${result.summary.nonBreakingChanges} |`,
    );
    lines.push(
      `| ${this.getTypeBadge(ChangeType.ADDITION)} Additions | ${result.summary.additions} |`,
    );
    lines.push("");

    // Warning message if breaking changes
    if (result.hasBreakingChanges) {
      lines.push(
        `> **Warning**\n> ${result.summary.breakingChanges} breaking change(s) detected - Major version bump required\n`,
      );
    }

    return lines.join("\n");
  }

  /**
   * Generate section for a single package
   */
  private generatePackageSection(pkg: PackageAnalysis): string {
    const lines: string[] = [];

    // Package header
    lines.push(`## ${pkg.packageName}\n`);

    // Version info. When previous === current the PR hasn't bumped yet, so an
    // arrow would be misleading; show the current version and project the
    // target version implied by the recommended bump instead.
    const versionUnchanged = pkg.version.previous === pkg.version.current;
    if (versionUnchanged) {
      lines.push(`**Current version:** ${pkg.version.current}`);
    } else {
      lines.push(
        `**Version:** ${pkg.version.previous} → ${pkg.version.current}`,
      );
    }

    const bumpLabel = pkg.recommendedVersionBump.toUpperCase();
    const targetVersion = versionUnchanged
      ? this.versionAnalyzer.applyBump(
          pkg.version.current,
          pkg.recommendedVersionBump,
        )
      : null;
    lines.push(
      targetVersion
        ? `**Recommended bump:** ${bumpLabel} → ${targetVersion}`
        : `**Recommended bump:** ${bumpLabel}`,
    );

    if (pkg.actualVersionBump) {
      const bumpIndicator = pkg.isValidBump ? "✅" : "❌";
      const suffix = pkg.isValidBump ? "" : " (insufficient)";
      lines.push(
        `**Actual bump:** ${pkg.actualVersionBump.toUpperCase()} ${bumpIndicator}${suffix}`,
      );
    }
    lines.push("");

    // Group changes by subpath. A package using only the root export emits
    // no subpath subheader to preserve the original report shape.
    const subpathGroups = new Map<string, ApiChange[]>();
    for (const change of pkg.changes) {
      const key = change.subpath ?? ".";
      const bucket = subpathGroups.get(key);
      if (bucket) bucket.push(change);
      else subpathGroups.set(key, [change]);
    }

    const orderedSubpaths = Array.from(subpathGroups.keys()).sort((a, b) => {
      if (a === b) return 0;
      if (a === ".") return -1;
      if (b === ".") return 1;
      return a.localeCompare(b);
    });

    const onlyRoot = orderedSubpaths.length === 1 && orderedSubpaths[0] === ".";

    for (const subpath of orderedSubpaths) {
      const changes = subpathGroups.get(subpath) ?? [];
      if (changes.length === 0) continue;

      if (!onlyRoot) {
        lines.push(`### Subpath \`${subpath}\`\n`);
      }

      lines.push(this.generateGroupedSections(changes, onlyRoot ? 3 : 4));
    }

    return lines.join("\n");
  }

  /**
   * Render breaking / non-breaking / additions sections for a single bucket
   * of changes (used per subpath group).
   */
  private generateGroupedSections(
    changes: ApiChange[],
    headingLevel: number,
  ): string {
    const lines: string[] = [];

    const breaking = changes.filter((c) => c.type === ChangeType.BREAKING);
    const nonBreaking = changes.filter(
      (c) => c.type === ChangeType.NON_BREAKING,
    );
    const additions = changes.filter((c) => c.type === ChangeType.ADDITION);

    if (breaking.length > 0) {
      lines.push(
        this.generateChangeSection(
          `${this.getTypeBadge(ChangeType.BREAKING)} Breaking Changes`,
          breaking,
          headingLevel,
        ),
      );
    }
    if (nonBreaking.length > 0) {
      lines.push(
        this.generateChangeSection(
          `${this.getTypeBadge(ChangeType.NON_BREAKING)} Non-breaking Changes`,
          nonBreaking,
          headingLevel,
        ),
      );
    }
    if (additions.length > 0) {
      lines.push(
        this.generateChangeSection(
          `${this.getTypeBadge(ChangeType.ADDITION)} Additions`,
          additions,
          headingLevel,
        ),
      );
    }

    return lines.join("\n");
  }

  /**
   * Generate a section for a group of changes
   */
  private generateChangeSection(
    title: string,
    changes: ApiChange[],
    headingLevel: number = 3,
  ): string {
    const lines: string[] = [];

    const hashes = "#".repeat(headingLevel);
    lines.push(`${hashes} ${title} (${changes.length})\n`);

    // Use collapsible section if too many changes
    const shouldCollapse = changes.length > this.collapseThreshold;

    if (shouldCollapse) {
      lines.push("<details>");
      lines.push(
        `<summary>Click to expand ${changes.length} changes</summary>\n`,
      );
    }

    for (const change of changes) {
      lines.push(this.formatChange(change, headingLevel + 1));
    }

    if (shouldCollapse) {
      lines.push("</details>\n");
    }

    return lines.join("\n");
  }

  /**
   * Format a single change with before/after diff
   */
  private formatChange(change: ApiChange, headingLevel: number = 4): string {
    const lines: string[] = [];

    // Change title
    const action = this.getChangeAction(change.type);
    const tag = this.aiHeadingTag(change);
    const hashes = "#".repeat(headingLevel);
    lines.push(`${hashes} ${action}: \`${change.name}\`${tag}\n`);

    // Code diff
    if (change.beforeSnippet || change.afterSnippet) {
      const beforeLines = change.beforeSnippet
        ? change.beforeSnippet.trim().split("\n")
        : [];
      const afterLines = change.afterSnippet
        ? change.afterSnippet.trim().split("\n")
        : [];
      const rendered = this.renderUnifiedDiff(beforeLines, afterLines);
      const collapsed = rendered.length > this.snippetMaxLines;

      if (collapsed) {
        lines.push("<details>");
        lines.push(
          `<summary>Diff (before: ${beforeLines.length} lines, after: ${afterLines.length} lines). Click to expand.</summary>\n`,
        );
      }

      lines.push("```diff");
      for (const line of rendered) {
        lines.push(line);
      }
      lines.push("```");

      if (collapsed) {
        lines.push("</details>\n");
      } else {
        lines.push("");
      }
    }

    // Description. When the AI also reviewed this same change, label the
    // rule-based description as the static analyzer's voice so the AI block
    // below reads as a distinct opinion rather than a contradiction.
    const ai = change.aiAnalysis;
    const labelStatic = ai && ai.source !== "ai-discovered";
    const prefix = labelStatic ? "**Static analyzer:** " : "";
    lines.push(`> ${prefix}${change.description}\n`);

    if (ai) {
      const confidence = Math.round(ai.confidence * 100);
      const label = this.aiReviewLabel(change);
      lines.push(`> 🤖 **${label}** (${confidence}%): ${ai.rationale}\n`);
      if (ai.migration) {
        lines.push(`> **Migration:** ${ai.migration}\n`);
      }
    }

    return lines.join("\n");
  }

  /**
   * Render a unified-style diff between two snippets. Anchors on the aligned
   * common prefix and suffix so a tiny edit inside a huge type alias renders
   * as the changed lines plus a few context lines, instead of the entire
   * before-and-after walls of text. The middle hunk is rendered as a
   * line-level diff (LCS) when small enough; otherwise it falls back to
   * head+tail bulk delete + add. Lines are prefixed for a ```diff fence:
   * "  " for context, "- " for removed, "+ " for added.
   */
  private renderUnifiedDiff(
    beforeLines: string[],
    afterLines: string[],
  ): string[] {
    const context = 3;

    // Aligned common prefix
    let prefix = 0;
    const minLen = Math.min(beforeLines.length, afterLines.length);
    while (prefix < minLen && beforeLines[prefix] === afterLines[prefix]) {
      prefix++;
    }

    // Aligned common suffix (must not overlap the prefix on either side)
    let suffix = 0;
    const maxSuffix = Math.min(
      beforeLines.length - prefix,
      afterLines.length - prefix,
    );
    while (
      suffix < maxSuffix &&
      beforeLines[beforeLines.length - 1 - suffix] ===
        afterLines[afterLines.length - 1 - suffix]
    ) {
      suffix++;
    }

    const beforeMid = beforeLines.slice(prefix, beforeLines.length - suffix);
    const afterMid = afterLines.slice(prefix, afterLines.length - suffix);

    const out: string[] = [];

    // Leading context: last few lines of common prefix, with elision marker
    // for whatever sits above the context window.
    if (prefix > 0) {
      const ctxLen = Math.min(context, prefix);
      const ctxStart = prefix - ctxLen;
      if (ctxStart > 0) {
        out.push(this.elisionMarker(ctxStart));
      }
      for (let i = ctxStart; i < prefix; i++) {
        out.push(`  ${beforeLines[i]}`);
      }
    }

    // Middle: line-level diff when the LCS table fits in budget AND the
    // resulting diff stays compact. If the two sides share little structure,
    // LCS degenerates to "delete everything, then add everything" which is
    // no better than the bulk fallback, so we skip it past a size cap.
    const lcsBudget = 500 * 500;
    const middleBudget = this.snippetMaxLines * 2;
    let usedLcs = false;
    if (beforeMid.length * afterMid.length <= lcsBudget) {
      const ops = this.lineDiff(beforeMid, afterMid);
      const changedOps = ops.reduce(
        (n, op) => (op.kind === "ctx" ? n : n + 1),
        0,
      );
      if (changedOps <= middleBudget) {
        for (const op of ops) {
          const marker =
            op.kind === "ctx" ? "  " : op.kind === "del" ? "- " : "+ ";
          out.push(`${marker}${op.line}`);
        }
        usedLcs = true;
      }
    }
    if (!usedLcs) {
      for (const line of this.headTail(beforeMid, this.snippetMaxLines)) {
        out.push(line.startsWith("// ...") ? line : `- ${line}`);
      }
      for (const line of this.headTail(afterMid, this.snippetMaxLines)) {
        out.push(line.startsWith("// ...") ? line : `+ ${line}`);
      }
    }

    // Trailing context: first few lines of common suffix, with elision
    // marker for whatever sits below the context window.
    if (suffix > 0) {
      const ctxLen = Math.min(context, suffix);
      for (let i = 0; i < ctxLen; i++) {
        out.push(`  ${beforeLines[beforeLines.length - suffix + i]}`);
      }
      const remaining = suffix - ctxLen;
      if (remaining > 0) {
        out.push(this.elisionMarker(remaining));
      }
    }

    return out;
  }

  private elisionMarker(count: number): string {
    return `// ... ${count} unchanged line${count === 1 ? "" : "s"} elided ...`;
  }

  private headTail(lines: string[], max: number): string[] {
    if (lines.length <= max) return lines;
    const half = Math.max(1, Math.floor(max / 2));
    const head = lines.slice(0, half);
    const tail = lines.slice(lines.length - half);
    const elided = lines.length - head.length - tail.length;
    return [
      ...head,
      `// ... ${elided} more line${elided === 1 ? "" : "s"} elided ...`,
      ...tail,
    ];
  }

  // Longest-common-subsequence line diff. O(m*n) time and space; caller
  // gates by lcsBudget so we don't run this on pathologically large inputs.
  private lineDiff(
    a: string[],
    b: string[],
  ): { kind: "ctx" | "del" | "add"; line: string }[] {
    const m = a.length;
    const n = b.length;
    if (m === 0) return b.map((line) => ({ kind: "add" as const, line }));
    if (n === 0) return a.map((line) => ({ kind: "del" as const, line }));

    const dp: number[][] = [];
    for (let i = 0; i <= m; i++) dp.push(new Array(n + 1).fill(0));
    for (let i = 1; i <= m; i++) {
      for (let j = 1; j <= n; j++) {
        if (a[i - 1] === b[j - 1]) dp[i][j] = dp[i - 1][j - 1] + 1;
        else dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);
      }
    }

    const ops: { kind: "ctx" | "del" | "add"; line: string }[] = [];
    let i = m;
    let j = n;
    while (i > 0 || j > 0) {
      if (i > 0 && j > 0 && a[i - 1] === b[j - 1]) {
        ops.push({ kind: "ctx", line: a[i - 1] });
        i--;
        j--;
      } else if (j > 0 && (i === 0 || dp[i][j - 1] >= dp[i - 1][j])) {
        ops.push({ kind: "add", line: b[j - 1] });
        j--;
      } else {
        ops.push({ kind: "del", line: a[i - 1] });
        i--;
      }
    }
    ops.reverse();
    return ops;
  }

  private aiHeadingTag(change: ApiChange): string {
    const ai = change.aiAnalysis;
    if (!ai) return "";
    if (ai.source === "ai-discovered") {
      return ` _(detected by AI)_`;
    }
    return "";
  }

  private aiReviewLabel(change: ApiChange): string {
    const ai = change.aiAnalysis;
    if (!ai) return "AI review";
    switch (ai.source) {
      case "rule-overridden":
        return `AI review (reclassified as ${change.type})`;
      case "rule-confirmed":
        return "AI review (confirmed)";
      case "ai-discovered":
        return "AI review (additional finding)";
    }
  }

  private firstAiModel(result: AnalysisResult): string | null {
    for (const pkg of result.packages) {
      if (pkg.aiReviewedBy) return pkg.aiReviewedBy;
      for (const change of pkg.changes) {
        if (change.aiAnalysis) return change.aiAnalysis.model;
      }
    }
    return null;
  }

  /**
   * Get action word for change type
   */
  private getChangeAction(type: ChangeType): string {
    switch (type) {
      case ChangeType.BREAKING:
        return "Changed";
      case ChangeType.NON_BREAKING:
        return "Modified";
      case ChangeType.ADDITION:
        return "Added";
      default:
        return "Changed";
    }
  }

  /**
   * Get emoji badge for change type
   */
  private getTypeBadge(type: ChangeType): string {
    switch (type) {
      case ChangeType.BREAKING:
        return "🔴";
      case ChangeType.NON_BREAKING:
        return "🟡";
      case ChangeType.ADDITION:
        return "🟢";
      default:
        return "⚪";
    }
  }

  /**
   * Get emoji badge for severity
   */
  getSeverityBadge(severity: ChangeSeverity): string {
    switch (severity) {
      case ChangeSeverity.MAJOR:
        return "🔴";
      case ChangeSeverity.MINOR:
        return "🟡";
      case ChangeSeverity.PATCH:
        return "🟢";
      default:
        return "⚪";
    }
  }
}
